[package]
name = "my-ring-vrf"
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ark-ec-vrfs = { git = "https://github.com/davxy/ark-ec-vrfs.git",  features = ["bandersnatch", "ring"], version = "0.1.2" }
ark-serialize = "0.3" 
hex = "0.4.3"
libc = "0.2"


